# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from PIL import Image
from pathlib import Path
from pngmeta import PngMeta
from typing import Any
from typing_extensions import Self
import base64
import json
import os
import shutil
import sys
import uuid
import webview

class api:
    def get_uuid(self: Self) -> Any: ...
    def get_json(self: Self) -> Any: ...
    def get_png(self: Self) -> Any: ...
    def save_file(self: Self, j: str) -> Any: ...
    def set_png(self: Self) -> Any: ...

def __nuitka_main__() -> Any:
    ...

html = f'{os.path.dirname(os.path.abspath(__file__))}/ui/dist/index.html'

__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import pngmeta
import pngmeta.PngMeta
import pathlib
import PIL
import PIL.Image
import webview
import base64
import shutil
import uuid
import json
import sys
import os